class StoreData < ActiveRecord::Migration[5.1]
  def change

    # The following two lines of code are needed to be commented out when
    # database initially has Game objects, and deleted_all executed.
    # if not, the error cause new Game object created have index not starting from #1

    # Game.destroy_all
    # Game.reset_pk_sequence
    values = [{homeTeamName: 'Atlanta Hawks', awayTeamName: 'New York Knicks', gameWinnerId: 20, homeTeamScore: 131, awayTeamScore: 136, gameDate: '2020-03-11'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 84, awayTeamScore: 98, gameDate: '2020-07-24'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Phoenix Suns', gameWinnerId: 2, homeTeamScore: 117, awayTeamScore: 103, gameDate: '2020-07-26'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Boston Celtics', gameWinnerId: 11, homeTeamScore: 137, awayTeamScore: 112, gameDate: '2020-07-29'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Boston Celtics', gameWinnerId: 17, homeTeamScore: 119, awayTeamScore: 112, gameDate: '2020-07-31'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 2, homeTeamScore: 128, awayTeamScore: 124, gameDate: '2020-08-02'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 112, awayTeamScore: 106, gameDate: '2020-08-04'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Brooklyn Nets', gameWinnerId: 2, homeTeamScore: 149, awayTeamScore: 115, gameDate: '2020-08-06'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 100, awayTeamScore: 122, gameDate: '2020-08-08'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Orlando Magic', gameWinnerId: 2, homeTeamScore: 122, awayTeamScore: 119, gameDate: '2020-08-09'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 107, awayTeamScore: 122, gameDate: '2020-08-11'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Washington Wizards', gameWinnerId: 30, homeTeamScore: 90, awayTeamScore: 96, gameDate: '2020-08-13'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 2, homeTeamScore: 109, awayTeamScore: 101, gameDate: '2020-08-17'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 2, homeTeamScore: 128, awayTeamScore: 101, gameDate: '2020-08-19'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 94, awayTeamScore: 102, gameDate: '2020-08-21'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 106, awayTeamScore: 110, gameDate: '2020-08-23'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 94, awayTeamScore: 112, gameDate: '2020-08-30'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 99, awayTeamScore: 102, gameDate: '2020-09-01'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 103, awayTeamScore: 104, gameDate: '2020-09-03'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 93, awayTeamScore: 100, gameDate: '2020-09-05'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 89, awayTeamScore: 111, gameDate: '2020-09-07'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 117, gameDate: '2020-09-15'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 101, awayTeamScore: 106, gameDate: '2020-09-17'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 106, awayTeamScore: 117, gameDate: '2020-09-20'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 112, awayTeamScore: 109, gameDate: '2020-09-24'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 2, homeTeamScore: 121, awayTeamScore: 108, gameDate: '2020-09-26'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 125, awayTeamScore: 113, gameDate: '2020-09-27'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 102, awayTeamScore: 104, gameDate: '2020-03-11'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 19, homeTeamScore: 68, awayTeamScore: 99, gameDate: '2020-07-22'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 119, awayTeamScore: 124, gameDate: '2020-07-25'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 107, awayTeamScore: 112, gameDate: '2020-07-27'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 118, awayTeamScore: 128, gameDate: '2020-07-31'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Washington Wizards', gameWinnerId: 3, homeTeamScore: 118, awayTeamScore: 110, gameDate: '2020-08-02'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 116, awayTeamScore: 119, gameDate: '2020-08-04'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Brooklyn Nets', gameWinnerId: 2, homeTeamScore: 149, awayTeamScore: 115, gameDate: '2020-08-06'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Sacramento Kings', gameWinnerId: 3, homeTeamScore: 119, awayTeamScore: 106, gameDate: '2020-08-07'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 120, awayTeamScore: 129, gameDate: '2020-08-10'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 96, awayTeamScore: 108, gameDate: '2020-08-11'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 133, awayTeamScore: 134, gameDate: '2020-08-14'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Brooklyn Nets', gameWinnerId: 28, homeTeamScore: 134, awayTeamScore: 110, gameDate: '2020-08-17'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Brooklyn Nets', gameWinnerId: 28, homeTeamScore: 104, awayTeamScore: 99, gameDate: '2020-08-19'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 92, awayTeamScore: 117, gameDate: '2020-08-21'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 150, gameDate: '2020-08-23'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Charlotte Hornets', gameWinnerId: 4, homeTeamScore: 98, awayTeamScore: 109, gameDate: '2020-03-11'},
      {homeTeamName: 'Chicago Bulls', awayTeamName: 'Cleveland Cavaliers', gameWinnerId: 5, homeTeamScore: 108, awayTeamScore: 103, gameDate: '2020-03-11'},
      {homeTeamName: 'Chicago Bulls', awayTeamName: 'Cleveland Cavaliers', gameWinnerId: 5, homeTeamScore: 108, awayTeamScore: 103, gameDate: '2020-03-11'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Dallas Mavericks', gameWinnerId: 27, homeTeamScore: 119, awayTeamScore: 109, gameDate: '2020-03-11'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Denver Nuggets', gameWinnerId: 7, homeTeamScore: 113, awayTeamScore: 97, gameDate: '2020-03-12'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 104, awayTeamScore: 108, gameDate: '2020-07-23'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 111, awayTeamScore: 118, gameDate: '2020-07-26'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 115, awayTeamScore: 118, gameDate: '2020-07-29'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 149, awayTeamScore: 153, gameDate: '2020-08-01'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Dallas Mavericks', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 115, gameDate: '2020-08-03'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 110, awayTeamScore: 114, gameDate: '2020-08-04'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 111, awayTeamScore: 126, gameDate: '2020-08-06'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 7, homeTeamScore: 136, awayTeamScore: 132, gameDate: '2020-08-09'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 114, awayTeamScore: 122, gameDate: '2020-08-10'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 131, awayTeamScore: 134, gameDate: '2020-08-11'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Dallas Mavericks', gameWinnerId: 24, homeTeamScore: 128, awayTeamScore: 102, gameDate: '2020-08-13'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 13, homeTeamScore: 118, awayTeamScore: 110, gameDate: '2020-08-18'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 114, awayTeamScore: 127, gameDate: '2020-08-20'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 122, awayTeamScore: 130, gameDate: '2020-08-22'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 7, homeTeamScore: 135, awayTeamScore: 133, gameDate: '2020-08-23'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 13, homeTeamScore: 154, awayTeamScore: 111, gameDate: '2020-08-26'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 97, awayTeamScore: 111, gameDate: '2020-08-30'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Denver Nuggets', gameWinnerId: 7, homeTeamScore: 113, awayTeamScore: 97, gameDate: '2020-03-12'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Washington Wizards', gameWinnerId: 8, homeTeamScore: 89, awayTeamScore: 82, gameDate: '2020-07-22'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Denver Nuggets', gameWinnerId: 19, homeTeamScore: 119, awayTeamScore: 104, gameDate: '2020-07-26'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 110, awayTeamScore: 114, gameDate: '2020-07-27'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 105, awayTeamScore: 125, gameDate: '2020-08-01'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 113, awayTeamScore: 121, gameDate: '2020-08-03'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 126, awayTeamScore: 132, gameDate: '2020-08-05'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 115, awayTeamScore: 125, gameDate: '2020-08-07'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 134, awayTeamScore: 132, gameDate: '2020-08-08'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 124, awayTeamScore: 121, gameDate: '2020-08-11'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 111, awayTeamScore: 124, gameDate: '2020-08-13'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Denver Nuggets', gameWinnerId: 28, homeTeamScore: 117, awayTeamScore: 109, gameDate: '2020-08-14'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 135, awayTeamScore: 125, gameDate: '2020-08-17'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 105, awayTeamScore: 124, gameDate: '2020-08-19'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 29, homeTeamScore: 124, awayTeamScore: 87, gameDate: '2020-08-21'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 29, homeTeamScore: 129, awayTeamScore: 127, gameDate: '2020-08-24'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 117, awayTeamScore: 107, gameDate: '2020-08-25'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 107, awayTeamScore: 119, gameDate: '2020-08-31'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 80, awayTeamScore: 78, gameDate: '2020-09-02'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 13, homeTeamScore: 120, awayTeamScore: 97, gameDate: '2020-09-04'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 101, awayTeamScore: 110, gameDate: '2020-09-06'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 113, gameDate: '2020-09-08'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 8, homeTeamScore: 111, awayTeamScore: 98, gameDate: '2020-09-13'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 89, awayTeamScore: 104, gameDate: '2020-09-16'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 126, awayTeamScore: 114, gameDate: '2020-09-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 126, awayTeamScore: 114, gameDate: '2020-09-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 105, awayTeamScore: 103, gameDate: '2020-09-20'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 8, homeTeamScore: 114, awayTeamScore: 106, gameDate: '2020-09-23'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 8, homeTeamScore: 114, awayTeamScore: 106, gameDate: '2020-09-23'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 114, gameDate: '2020-09-25'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 114, gameDate: '2020-09-25'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 117, awayTeamScore: 107, gameDate: '2020-09-27'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Detroit Pistons', gameWinnerId: 23, homeTeamScore: 124, awayTeamScore: 106, gameDate: '2020-03-11'},
      {homeTeamName: 'Golden State Warriors', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 131, gameDate: '2020-03-11'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Minnesota Timberwolves', gameWinnerId: 11, homeTeamScore: 117, awayTeamScore: 111, gameDate: '2020-03-11'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Houston Rockets', gameWinnerId: 28, homeTeamScore: 94, awayTeamScore: 83, gameDate: '2020-07-24'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 104, awayTeamScore: 119, gameDate: '2020-07-27'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Boston Celtics', gameWinnerId: 11, homeTeamScore: 137, awayTeamScore: 112, gameDate: '2020-07-29'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 149, awayTeamScore: 153, gameDate: '2020-08-01'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 11, homeTeamScore: 120, awayTeamScore: 116, gameDate: '2020-08-03'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Houston Rockets', gameWinnerId: 25, homeTeamScore: 110, awayTeamScore: 102, gameDate: '2020-08-05'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 11, homeTeamScore: 113, awayTeamScore: 97, gameDate: '2020-08-07'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 112, awayTeamScore: 129, gameDate: '2020-08-10'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Houston Rockets', gameWinnerId: 27, homeTeamScore: 123, awayTeamScore: 105, gameDate: '2020-08-11'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 104, awayTeamScore: 108, gameDate: '2020-08-12'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 23, homeTeamScore: 96, awayTeamScore: 134, gameDate: '2020-08-15'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 123, awayTeamScore: 108, gameDate: '2020-08-18'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 111, awayTeamScore: 98, gameDate: '2020-08-20'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 119, awayTeamScore: 107, gameDate: '2020-08-22'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 117, awayTeamScore: 114, gameDate: '2020-08-24'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 114, awayTeamScore: 80, gameDate: '2020-08-29'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 104, awayTeamScore: 100, gameDate: '2020-09-01'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 104, awayTeamScore: 102, gameDate: '2020-09-03'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 97, awayTeamScore: 112, gameDate: '2020-09-05'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 117, awayTeamScore: 109, gameDate: '2020-09-07'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 102, awayTeamScore: 112, gameDate: '2020-09-09'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 100, awayTeamScore: 110, gameDate: '2020-09-10'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 100, awayTeamScore: 110, gameDate: '2020-09-10'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 12, homeTeamScore: 91, awayTeamScore: 88, gameDate: '2020-07-23'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 111, awayTeamScore: 118, gameDate: '2020-07-26'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 111, awayTeamScore: 118, gameDate: '2020-07-28'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 12, homeTeamScore: 127, awayTeamScore: 121, gameDate: '2020-08-01'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 100, awayTeamScore: 111, gameDate: '2020-08-03'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Orlando Magic', gameWinnerId: 12, homeTeamScore: 120, awayTeamScore: 109, gameDate: '2020-08-04'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Indiana Pacers', gameWinnerId: 24, homeTeamScore: 114, awayTeamScore: 99, gameDate: '2020-08-06'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 12, homeTeamScore: 116, awayTeamScore: 111, gameDate: '2020-08-08'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 92, gameDate: '2020-08-11'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 104, awayTeamScore: 108, gameDate: '2020-08-12'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 12, homeTeamScore: 109, awayTeamScore: 92, gameDate: '2020-08-14'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 101, awayTeamScore: 113, gameDate: '2020-08-18'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 100, awayTeamScore: 109, gameDate: '2020-08-20'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 124, awayTeamScore: 115, gameDate: '2020-08-22'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 99, awayTeamScore: 87, gameDate: '2020-08-24'},
      {homeTeamName: 'Golden State Warriors', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 131, gameDate: '2020-03-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Orlando Magic', gameWinnerId: 13, homeTeamScore: 99, awayTeamScore: 90, gameDate: '2020-07-22'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 100, awayTeamScore: 105, gameDate: '2020-07-26'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Sacramento Kings', gameWinnerId: 26, homeTeamScore: 102, awayTeamScore: 106, gameDate: '2020-07-27'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'LA Clippers', gameWinnerId: 14, homeTeamScore: 103, awayTeamScore: 101, gameDate: '2020-07-31'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 13, homeTeamScore: 126, awayTeamScore: 103, gameDate: '2020-08-01'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 115, awayTeamScore: 117, gameDate: '2020-08-04'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 111, awayTeamScore: 126, gameDate: '2020-08-06'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 117, awayTeamScore: 122, gameDate: '2020-08-08'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 120, awayTeamScore: 129, gameDate: '2020-08-10'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 111, awayTeamScore: 124, gameDate: '2020-08-13'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 103, gameDate: '2020-08-14'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 13, homeTeamScore: 118, awayTeamScore: 110, gameDate: '2020-08-18'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 114, awayTeamScore: 127, gameDate: '2020-08-20'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 122, awayTeamScore: 130, gameDate: '2020-08-22'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 7, homeTeamScore: 135, awayTeamScore: 133, gameDate: '2020-08-23'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 13, homeTeamScore: 154, awayTeamScore: 111, gameDate: '2020-08-26'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 97, awayTeamScore: 111, gameDate: '2020-08-30'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 13, homeTeamScore: 120, awayTeamScore: 97, gameDate: '2020-09-04'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 101, awayTeamScore: 110, gameDate: '2020-09-06'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 113, gameDate: '2020-09-08'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 85, awayTeamScore: 96, gameDate: '2020-09-10'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 105, awayTeamScore: 111, gameDate: '2020-09-11'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'LA Clippers', gameWinnerId: 8, homeTeamScore: 111, awayTeamScore: 98, gameDate: '2020-09-13'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 89, awayTeamScore: 104, gameDate: '2020-09-16'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 102, awayTeamScore: 104, gameDate: '2020-03-11'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 104, awayTeamScore: 108, gameDate: '2020-07-23'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 112, awayTeamScore: 119, gameDate: '2020-07-25'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Washington Wizards', gameWinnerId: 14, homeTeamScore: 123, awayTeamScore: 116, gameDate: '2020-07-27'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'LA Clippers', gameWinnerId: 14, homeTeamScore: 103, awayTeamScore: 101, gameDate: '2020-07-31'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 28, homeTeamScore: 107, awayTeamScore: 92, gameDate: '2020-08-02'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 116, gameDate: '2020-08-04'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 86, awayTeamScore: 105, gameDate: '2020-08-05'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 11, homeTeamScore: 113, awayTeamScore: 97, gameDate: '2020-08-07'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 12, homeTeamScore: 116, awayTeamScore: 111, gameDate: '2020-08-08'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 124, awayTeamScore: 121, gameDate: '2020-08-11'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Sacramento Kings', gameWinnerId: 26, homeTeamScore: 122, awayTeamScore: 136, gameDate: '2020-08-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 93, awayTeamScore: 100, gameDate: '2020-08-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 14, homeTeamScore: 111, awayTeamScore: 88, gameDate: '2020-08-21'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 116, gameDate: '2020-08-23'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 115, awayTeamScore: 135, gameDate: '2020-08-25'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 14, homeTeamScore: 131, awayTeamScore: 122, gameDate: '2020-08-30'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 97, awayTeamScore: 112, gameDate: '2020-09-05'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 117, awayTeamScore: 109, gameDate: '2020-09-07'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 102, awayTeamScore: 112, gameDate: '2020-09-09'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 100, awayTeamScore: 110, gameDate: '2020-09-10'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 100, awayTeamScore: 110, gameDate: '2020-09-10'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Houston Rockets', gameWinnerId: 14, homeTeamScore: 119, awayTeamScore: 96, gameDate: '2020-09-13'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 126, awayTeamScore: 114, gameDate: '2020-09-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 126, awayTeamScore: 114, gameDate: '2020-09-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 105, awayTeamScore: 103, gameDate: '2020-09-20'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 8, homeTeamScore: 114, awayTeamScore: 106, gameDate: '2020-09-23'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 8, homeTeamScore: 114, awayTeamScore: 106, gameDate: '2020-09-23'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 114, gameDate: '2020-09-25'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 114, gameDate: '2020-09-25'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Denver Nuggets', gameWinnerId: 14, homeTeamScore: 117, awayTeamScore: 107, gameDate: '2020-09-27'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 14, homeTeamScore: 116, awayTeamScore: 98, gameDate: '2020-10-01'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 14, homeTeamScore: 124, awayTeamScore: 114, gameDate: '2020-10-03'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 16, homeTeamScore: 115, awayTeamScore: 104, gameDate: '2020-10-04'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 96, awayTeamScore: 102, gameDate: '2020-10-07'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 108, awayTeamScore: 111, gameDate: '2020-10-10'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 93, awayTeamScore: 106, gameDate: '2020-10-11'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 115, awayTeamScore: 120, gameDate: '2020-03-11'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 23, homeTeamScore: 90, awayTeamScore: 83, gameDate: '2020-07-24'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 104, awayTeamScore: 119, gameDate: '2020-07-27'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 15, homeTeamScore: 110, awayTeamScore: 128, gameDate: '2020-07-28'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 25, homeTeamScore: 140, awayTeamScore: 135, gameDate: '2020-07-31'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 106, awayTeamScore: 108, gameDate: '2020-08-02'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 19, homeTeamScore: 109, awayTeamScore: 99, gameDate: '2020-08-03'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 29, homeTeamScore: 124, awayTeamScore: 115, gameDate: '2020-08-05'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 15, homeTeamScore: 121, awayTeamScore: 92, gameDate: '2020-08-07'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 28, homeTeamScore: 108, awayTeamScore: 99, gameDate: '2020-08-09'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 107, awayTeamScore: 122, gameDate: '2020-08-11'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 15, homeTeamScore: 119, awayTeamScore: 106, gameDate: '2020-08-13'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 25, homeTeamScore: 126, awayTeamScore: 122, gameDate: '2020-08-15'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Charlotte Hornets', gameWinnerId: 4, homeTeamScore: 98, awayTeamScore: 109, gameDate: '2020-03-11'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Sacramento Kings', gameWinnerId: 16, homeTeamScore: 104, awayTeamScore: 98, gameDate: '2020-07-23'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Miami Heat', gameWinnerId: 29, homeTeamScore: 101, awayTeamScore: 99, gameDate: '2020-07-25'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 15, homeTeamScore: 110, awayTeamScore: 128, gameDate: '2020-07-28'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 105, awayTeamScore: 125, gameDate: '2020-08-01'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 103, awayTeamScore: 107, gameDate: '2020-08-03'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 112, awayTeamScore: 106, gameDate: '2020-08-04'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 17, homeTeamScore: 130, awayTeamScore: 116, gameDate: '2020-08-06'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 112, awayTeamScore: 119, gameDate: '2020-08-08'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 92, gameDate: '2020-08-11'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Miami Heat', gameWinnerId: 21, homeTeamScore: 116, awayTeamScore: 115, gameDate: '2020-08-13'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 12, homeTeamScore: 109, awayTeamScore: 92, gameDate: '2020-08-14'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 101, awayTeamScore: 113, gameDate: '2020-08-18'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 100, awayTeamScore: 109, gameDate: '2020-08-20'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 124, awayTeamScore: 115, gameDate: '2020-08-22'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Indiana Pacers', gameWinnerId: 16, homeTeamScore: 99, awayTeamScore: 87, gameDate: '2020-08-24'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 104, awayTeamScore: 115, gameDate: '2020-08-31'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 116, gameDate: '2020-09-02'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 16, homeTeamScore: 115, awayTeamScore: 100, gameDate: '2020-09-04'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 115, awayTeamScore: 118, gameDate: '2020-09-06'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 94, awayTeamScore: 103, gameDate: '2020-09-08'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 117, gameDate: '2020-09-15'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 101, awayTeamScore: 106, gameDate: '2020-09-17'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 106, awayTeamScore: 117, gameDate: '2020-09-20'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 112, awayTeamScore: 109, gameDate: '2020-09-24'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Miami Heat', gameWinnerId: 2, homeTeamScore: 121, awayTeamScore: 108, gameDate: '2020-09-26'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Boston Celtics', gameWinnerId: 16, homeTeamScore: 125, awayTeamScore: 113, gameDate: '2020-09-27'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 14, homeTeamScore: 116, awayTeamScore: 98, gameDate: '2020-10-01'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 14, homeTeamScore: 124, awayTeamScore: 114, gameDate: '2020-10-03'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 16, homeTeamScore: 115, awayTeamScore: 104, gameDate: '2020-10-04'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 96, awayTeamScore: 102, gameDate: '2020-10-07'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 108, awayTeamScore: 111, gameDate: '2020-10-10'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 93, awayTeamScore: 106, gameDate: '2020-10-11'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'San Antonio Spurs', gameWinnerId: 17, homeTeamScore: 113, awayTeamScore: 92, gameDate: '2020-07-23'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 123, awayTeamScore: 131, gameDate: '2020-07-25'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 19, homeTeamScore: 103, awayTeamScore: 124, gameDate: '2020-07-28'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Boston Celtics', gameWinnerId: 17, homeTeamScore: 119, awayTeamScore: 112, gameDate: '2020-07-31'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 11, homeTeamScore: 120, awayTeamScore: 116, gameDate: '2020-08-03'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 116, awayTeamScore: 119, gameDate: '2020-08-04'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 17, homeTeamScore: 130, awayTeamScore: 116, gameDate: '2020-08-06'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 7, homeTeamScore: 136, awayTeamScore: 132, gameDate: '2020-08-09'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 106, awayTeamScore: 114, gameDate: '2020-08-10'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 113, awayTeamScore: 126, gameDate: '2020-08-12'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 15, homeTeamScore: 119, awayTeamScore: 106, gameDate: '2020-08-13'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 110, awayTeamScore: 122, gameDate: '2020-08-18'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 17, homeTeamScore: 111, awayTeamScore: 96, gameDate: '2020-08-20'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 107, awayTeamScore: 121, gameDate: '2020-08-22'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 106, awayTeamScore: 121, gameDate: '2020-08-24'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 17, homeTeamScore: 118, awayTeamScore: 104, gameDate: '2020-08-29'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 104, awayTeamScore: 115, gameDate: '2020-08-31'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 114, awayTeamScore: 116, gameDate: '2020-09-02'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 16, homeTeamScore: 115, awayTeamScore: 100, gameDate: '2020-09-04'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 115, awayTeamScore: 118, gameDate: '2020-09-06'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Miami Heat', gameWinnerId: 16, homeTeamScore: 94, awayTeamScore: 103, gameDate: '2020-09-08'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Minnesota Timberwolves', gameWinnerId: 11, homeTeamScore: 117, awayTeamScore: 111, gameDate: '2020-03-11'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 19, homeTeamScore: 68, awayTeamScore: 99, gameDate: '2020-07-22'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Denver Nuggets', gameWinnerId: 19, homeTeamScore: 119, awayTeamScore: 104, gameDate: '2020-07-26'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 19, homeTeamScore: 103, awayTeamScore: 124, gameDate: '2020-07-28'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 104, awayTeamScore: 106, gameDate: '2020-07-30'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 13, homeTeamScore: 126, awayTeamScore: 103, gameDate: '2020-08-01'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 19, homeTeamScore: 109, awayTeamScore: 99, gameDate: '2020-08-03'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 26, homeTeamScore: 140, awayTeamScore: 125, gameDate: '2020-08-06'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Washington Wizards', gameWinnerId: 19, homeTeamScore: 118, awayTeamScore: 107, gameDate: '2020-08-08'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 113, awayTeamScore: 122, gameDate: '2020-08-09'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 26, homeTeamScore: 112, awayTeamScore: 106, gameDate: '2020-08-12'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 22, homeTeamScore: 133, awayTeamScore: 127, gameDate: '2020-08-14'},
      {homeTeamName: 'Atlanta Hawks', awayTeamName: 'New York Knicks', gameWinnerId: 20, homeTeamScore: 131, awayTeamScore: 136, gameDate: '2020-03-11'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 84, awayTeamScore: 98, gameDate: '2020-07-24'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 21, homeTeamScore: 102, awayTeamScore: 97, gameDate: '2020-07-26'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 120, awayTeamScore: 131, gameDate: '2020-07-28'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Utah Jazz', gameWinnerId: 21, homeTeamScore: 110, awayTeamScore: 94, gameDate: '2020-08-01'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 113, awayTeamScore: 121, gameDate: '2020-08-03'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 86, awayTeamScore: 105, gameDate: '2020-08-05'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 15, homeTeamScore: 121, awayTeamScore: 92, gameDate: '2020-08-07'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Washington Wizards', gameWinnerId: 21, homeTeamScore: 121, awayTeamScore: 103, gameDate: '2020-08-09'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 24, homeTeamScore: 128, awayTeamScore: 101, gameDate: '2020-08-10'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Miami Heat', gameWinnerId: 21, homeTeamScore: 116, awayTeamScore: 115, gameDate: '2020-08-13'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 13, homeTeamScore: 107, awayTeamScore: 103, gameDate: '2020-08-14'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 123, awayTeamScore: 108, gameDate: '2020-08-18'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 111, awayTeamScore: 98, gameDate: '2020-08-20'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 119, awayTeamScore: 107, gameDate: '2020-08-22'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 117, awayTeamScore: 114, gameDate: '2020-08-24'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 114, awayTeamScore: 80, gameDate: '2020-08-29'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Houston Rockets', gameWinnerId: 21, homeTeamScore: 104, awayTeamScore: 100, gameDate: '2020-09-01'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 11, homeTeamScore: 104, awayTeamScore: 102, gameDate: '2020-09-03'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 115, awayTeamScore: 120, gameDate: '2020-03-11'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Orlando Magic', gameWinnerId: 13, homeTeamScore: 99, awayTeamScore: 90, gameDate: '2020-07-22'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 112, awayTeamScore: 119, gameDate: '2020-07-25'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 110, awayTeamScore: 114, gameDate: '2020-07-27'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 118, awayTeamScore: 128, gameDate: '2020-07-31'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Sacramento Kings', gameWinnerId: 22, homeTeamScore: 132, awayTeamScore: 116, gameDate: '2020-08-02'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Orlando Magic', gameWinnerId: 12, homeTeamScore: 120, awayTeamScore: 109, gameDate: '2020-08-04'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 99, awayTeamScore: 109, gameDate: '2020-08-06'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Orlando Magic', gameWinnerId: 23, homeTeamScore: 108, awayTeamScore: 101, gameDate: '2020-08-07'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Orlando Magic', gameWinnerId: 2, homeTeamScore: 122, awayTeamScore: 119, gameDate: '2020-08-09'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 96, awayTeamScore: 108, gameDate: '2020-08-11'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 22, homeTeamScore: 133, awayTeamScore: 127, gameDate: '2020-08-14'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 22, homeTeamScore: 110, awayTeamScore: 122, gameDate: '2020-08-18'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 17, homeTeamScore: 111, awayTeamScore: 96, gameDate: '2020-08-20'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 107, awayTeamScore: 121, gameDate: '2020-08-22'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 106, awayTeamScore: 121, gameDate: '2020-08-24'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Orlando Magic', gameWinnerId: 17, homeTeamScore: 118, awayTeamScore: 104, gameDate: '2020-08-29'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Detroit Pistons', gameWinnerId: 23, homeTeamScore: 124, awayTeamScore: 106, gameDate: '2020-03-11'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 23, homeTeamScore: 90, awayTeamScore: 83, gameDate: '2020-07-24'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 21, homeTeamScore: 102, awayTeamScore: 97, gameDate: '2020-07-26'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 115, awayTeamScore: 118, gameDate: '2020-07-29'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 12, homeTeamScore: 127, awayTeamScore: 121, gameDate: '2020-08-01'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'San Antonio Spurs', gameWinnerId: 23, homeTeamScore: 132, awayTeamScore: 130, gameDate: '2020-08-04'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 23, homeTeamScore: 98, awayTeamScore: 107, gameDate: '2020-08-05'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Orlando Magic', gameWinnerId: 23, homeTeamScore: 108, awayTeamScore: 101, gameDate: '2020-08-07'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 25, homeTeamScore: 124, awayTeamScore: 121, gameDate: '2020-08-09'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 130, gameDate: '2020-08-11'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 121, awayTeamScore: 125, gameDate: '2020-08-12'},
      {homeTeamName: 'Houston Rockets', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 23, homeTeamScore: 96, awayTeamScore: 134, gameDate: '2020-08-15'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 2, homeTeamScore: 109, awayTeamScore: 101, gameDate: '2020-08-17'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 2, homeTeamScore: 128, awayTeamScore: 101, gameDate: '2020-08-19'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 94, awayTeamScore: 102, gameDate: '2020-08-21'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 106, awayTeamScore: 110, gameDate: '2020-08-23'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Phoenix Suns', gameWinnerId: 25, homeTeamScore: 121, awayTeamScore: 105, gameDate: '2020-03-11'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 88, awayTeamScore: 101, gameDate: '2020-07-24'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Phoenix Suns', gameWinnerId: 2, homeTeamScore: 117, awayTeamScore: 103, gameDate: '2020-07-26'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Toronto Raptors', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 106, gameDate: '2020-07-28'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 112, awayTeamScore: 125, gameDate: '2020-07-31'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Dallas Mavericks', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 115, gameDate: '2020-08-03'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 115, awayTeamScore: 117, gameDate: '2020-08-04'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Indiana Pacers', gameWinnerId: 24, homeTeamScore: 114, awayTeamScore: 99, gameDate: '2020-08-06'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 112, awayTeamScore: 119, gameDate: '2020-08-08'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 24, homeTeamScore: 128, awayTeamScore: 101, gameDate: '2020-08-10'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 130, gameDate: '2020-08-11'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Dallas Mavericks', gameWinnerId: 24, homeTeamScore: 128, awayTeamScore: 102, gameDate: '2020-08-13'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Phoenix Suns', gameWinnerId: 25, homeTeamScore: 121, awayTeamScore: 105, gameDate: '2020-03-11'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 12, homeTeamScore: 91, awayTeamScore: 88, gameDate: '2020-07-23'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 28, homeTeamScore: 110, awayTeamScore: 104, gameDate: '2020-07-26'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Oklahoma City Thunder', gameWinnerId: 21, homeTeamScore: 120, awayTeamScore: 131, gameDate: '2020-07-28'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 25, homeTeamScore: 140, awayTeamScore: 135, gameDate: '2020-07-31'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 2, homeTeamScore: 128, awayTeamScore: 124, gameDate: '2020-08-02'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Houston Rockets', gameWinnerId: 25, homeTeamScore: 110, awayTeamScore: 102, gameDate: '2020-08-05'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 115, awayTeamScore: 125, gameDate: '2020-08-07'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 117, awayTeamScore: 122, gameDate: '2020-08-08'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 25, homeTeamScore: 124, awayTeamScore: 121, gameDate: '2020-08-09'},
      {homeTeamName: 'Dallas Mavericks', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 131, awayTeamScore: 134, gameDate: '2020-08-11'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 133, awayTeamScore: 134, gameDate: '2020-08-14'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 25, homeTeamScore: 126, awayTeamScore: 122, gameDate: '2020-08-15'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 25, homeTeamScore: 93, awayTeamScore: 100, gameDate: '2020-08-19'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 14, homeTeamScore: 111, awayTeamScore: 88, gameDate: '2020-08-21'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 116, gameDate: '2020-08-23'},
      {homeTeamName: 'Portland Trail Blazers', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 115, awayTeamScore: 135, gameDate: '2020-08-25'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 14, homeTeamScore: 131, awayTeamScore: 122, gameDate: '2020-08-30'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Sacramento Kings', gameWinnerId: 16, homeTeamScore: 104, awayTeamScore: 98, gameDate: '2020-07-23'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 123, awayTeamScore: 131, gameDate: '2020-07-25'},
      {homeTeamName: 'LA Clippers', awayTeamName: 'Sacramento Kings', gameWinnerId: 26, homeTeamScore: 102, awayTeamScore: 106, gameDate: '2020-07-27'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Sacramento Kings', gameWinnerId: 27, homeTeamScore: 129, awayTeamScore: 120, gameDate: '2020-08-01'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Sacramento Kings', gameWinnerId: 22, homeTeamScore: 132, awayTeamScore: 116, gameDate: '2020-08-02'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 110, awayTeamScore: 114, gameDate: '2020-08-04'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 26, homeTeamScore: 140, awayTeamScore: 125, gameDate: '2020-08-06'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Sacramento Kings', gameWinnerId: 3, homeTeamScore: 119, awayTeamScore: 106, gameDate: '2020-08-07'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'Houston Rockets', gameWinnerId: 11, homeTeamScore: 112, awayTeamScore: 129, gameDate: '2020-08-10'},
      {homeTeamName: 'Sacramento Kings', awayTeamName: 'New Orleans Pelicans', gameWinnerId: 26, homeTeamScore: 112, awayTeamScore: 106, gameDate: '2020-08-12'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Sacramento Kings', gameWinnerId: 26, homeTeamScore: 122, awayTeamScore: 136, gameDate: '2020-08-13'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Dallas Mavericks', gameWinnerId: 27, homeTeamScore: 119, awayTeamScore: 109, gameDate: '2020-03-11'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'San Antonio Spurs', gameWinnerId: 17, homeTeamScore: 113, awayTeamScore: 92, gameDate: '2020-07-23'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Brooklyn Nets', gameWinnerId: 3, homeTeamScore: 119, awayTeamScore: 124, gameDate: '2020-07-25'},
      {homeTeamName: 'Indiana Pacers', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 111, awayTeamScore: 118, gameDate: '2020-07-28'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Sacramento Kings', gameWinnerId: 27, homeTeamScore: 129, awayTeamScore: 120, gameDate: '2020-08-01'},
      {homeTeamName: 'Memphis Grizzlies', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 106, awayTeamScore: 108, gameDate: '2020-08-02'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'San Antonio Spurs', gameWinnerId: 23, homeTeamScore: 132, awayTeamScore: 130, gameDate: '2020-08-04'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 126, awayTeamScore: 132, gameDate: '2020-08-05'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Utah Jazz', gameWinnerId: 27, homeTeamScore: 119, awayTeamScore: 111, gameDate: '2020-08-07'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'San Antonio Spurs', gameWinnerId: 27, homeTeamScore: 113, awayTeamScore: 122, gameDate: '2020-08-09'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Houston Rockets', gameWinnerId: 27, homeTeamScore: 123, awayTeamScore: 105, gameDate: '2020-08-11'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'San Antonio Spurs', gameWinnerId: 29, homeTeamScore: 118, awayTeamScore: 112, gameDate: '2020-08-13'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Houston Rockets', gameWinnerId: 28, homeTeamScore: 94, awayTeamScore: 83, gameDate: '2020-07-24'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Portland Trail Blazers', gameWinnerId: 28, homeTeamScore: 110, awayTeamScore: 104, gameDate: '2020-07-26'},
      {homeTeamName: 'Phoenix Suns', awayTeamName: 'Toronto Raptors', gameWinnerId: 24, homeTeamScore: 117, awayTeamScore: 106, gameDate: '2020-07-28'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 28, homeTeamScore: 107, awayTeamScore: 92, gameDate: '2020-08-02'},
      {homeTeamName: 'Miami Heat', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 103, awayTeamScore: 107, gameDate: '2020-08-03'},
      {homeTeamName: 'Orlando Magic', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 99, awayTeamScore: 109, gameDate: '2020-08-06'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 100, awayTeamScore: 122, gameDate: '2020-08-08'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 28, homeTeamScore: 108, awayTeamScore: 99, gameDate: '2020-08-09'},
      {homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 106, awayTeamScore: 114, gameDate: '2020-08-10'},
      {homeTeamName: 'Philadelphia 76ers', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 121, awayTeamScore: 125, gameDate: '2020-08-12'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Denver Nuggets', gameWinnerId: 28, homeTeamScore: 117, awayTeamScore: 109, gameDate: '2020-08-14'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Brooklyn Nets', gameWinnerId: 28, homeTeamScore: 134, awayTeamScore: 110, gameDate: '2020-08-17'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Brooklyn Nets', gameWinnerId: 28, homeTeamScore: 104, awayTeamScore: 99, gameDate: '2020-08-19'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 92, awayTeamScore: 117, gameDate: '2020-08-21'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 150, gameDate: '2020-08-23'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 94, awayTeamScore: 112, gameDate: '2020-08-30'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 99, awayTeamScore: 102, gameDate: '2020-09-01'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 103, awayTeamScore: 104, gameDate: '2020-09-03'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 93, awayTeamScore: 100, gameDate: '2020-09-05'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 89, awayTeamScore: 111, gameDate: '2020-09-07'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Toronto Raptors', gameWinnerId: 28, homeTeamScore: 122, awayTeamScore: 125, gameDate: '2020-09-09'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Toronto Raptors', awayTeamName: 'Boston Celtics', gameWinnerId: 2, homeTeamScore: 87, awayTeamScore: 92, gameDate: '2020-09-12'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 88, awayTeamScore: 101, gameDate: '2020-07-24'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Miami Heat', gameWinnerId: 29, homeTeamScore: 101, awayTeamScore: 99, gameDate: '2020-07-25'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 107, awayTeamScore: 112, gameDate: '2020-07-27'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 104, awayTeamScore: 106, gameDate: '2020-07-30'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Utah Jazz', gameWinnerId: 21, homeTeamScore: 110, awayTeamScore: 94, gameDate: '2020-08-01'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Los Angeles Lakers', gameWinnerId: 14, homeTeamScore: 108, awayTeamScore: 116, gameDate: '2020-08-04'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Memphis Grizzlies', gameWinnerId: 29, homeTeamScore: 124, awayTeamScore: 115, gameDate: '2020-08-05'},
      {homeTeamName: 'San Antonio Spurs', awayTeamName: 'Utah Jazz', gameWinnerId: 27, homeTeamScore: 119, awayTeamScore: 111, gameDate: '2020-08-07'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 134, awayTeamScore: 132, gameDate: '2020-08-08'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Dallas Mavericks', gameWinnerId: 7, homeTeamScore: 114, awayTeamScore: 122, gameDate: '2020-08-10'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'San Antonio Spurs', gameWinnerId: 29, homeTeamScore: 118, awayTeamScore: 112, gameDate: '2020-08-13'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 135, awayTeamScore: 125, gameDate: '2020-08-17'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 29, homeTeamScore: 105, awayTeamScore: 124, gameDate: '2020-08-19'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 29, homeTeamScore: 124, awayTeamScore: 87, gameDate: '2020-08-21'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 29, homeTeamScore: 129, awayTeamScore: 127, gameDate: '2020-08-24'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 117, awayTeamScore: 107, gameDate: '2020-08-25'},
      {homeTeamName: 'Utah Jazz', awayTeamName: 'Denver Nuggets', gameWinnerId: 8, homeTeamScore: 107, awayTeamScore: 119, gameDate: '2020-08-31'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Utah Jazz', gameWinnerId: 8, homeTeamScore: 80, awayTeamScore: 78, gameDate: '2020-09-02'},
      {homeTeamName: 'Denver Nuggets', awayTeamName: 'Washington Wizards', gameWinnerId: 8, homeTeamScore: 89, awayTeamScore: 82, gameDate: '2020-07-22'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'LA Clippers', gameWinnerId: 13, homeTeamScore: 100, awayTeamScore: 105, gameDate: '2020-07-26'},
      {homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Washington Wizards', gameWinnerId: 14, homeTeamScore: 123, awayTeamScore: 116, gameDate: '2020-07-27'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Phoenix Suns', gameWinnerId: 24, homeTeamScore: 112, awayTeamScore: 125, gameDate: '2020-07-31'},
      {homeTeamName: 'Brooklyn Nets', awayTeamName: 'Washington Wizards', gameWinnerId: 3, homeTeamScore: 118, awayTeamScore: 110, gameDate: '2020-08-02'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Indiana Pacers', gameWinnerId: 12, homeTeamScore: 100, awayTeamScore: 111, gameDate: '2020-08-03'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Philadelphia 76ers', gameWinnerId: 23, homeTeamScore: 98, awayTeamScore: 107, gameDate: '2020-08-05'},
      {homeTeamName: 'New Orleans Pelicans', awayTeamName: 'Washington Wizards', gameWinnerId: 19, homeTeamScore: 118, awayTeamScore: 107, gameDate: '2020-08-08'},
      {homeTeamName: 'Oklahoma City Thunder', awayTeamName: 'Washington Wizards', gameWinnerId: 21, homeTeamScore: 121, awayTeamScore: 103, gameDate: '2020-08-09'},
      {homeTeamName: 'Washington Wizards', awayTeamName: 'Milwaukee Bucks', gameWinnerId: 17, homeTeamScore: 113, awayTeamScore: 126, gameDate: '2020-08-12'},
      {homeTeamName: 'Boston Celtics', awayTeamName: 'Washington Wizards', gameWinnerId: 30, homeTeamScore: 90, awayTeamScore: 96, gameDate: '2020-08-13'}]
      
    Game.import values, validate: true
  end
end
